package com.varep.manystones.blocks.decor;

import com.varep.manystones.MSMod;
import com.varep.manystones.blocks.WorldBlocks;

import cpw.mods.fml.common.Mod.EventHandler;
import cpw.mods.fml.common.event.FMLPreInitializationEvent;
import cpw.mods.fml.common.registry.GameRegistry;
import net.minecraft.block.Block;
import net.minecraft.item.Item;
import net.minecraft.item.ItemBlock;

public class Decor {

	public static Item dark_concrete;
	public static Item light_concrete;
	
	public static Block ametist_block;
	
	public static Block smooth_diabaz;
	public static Block brick1_diabaz;
	public static Block brick2_diabaz;
	public static Block big_brick_diabaz;
	public static Block slab_diabaz;
	public static Block slab_smooth_diabaz;
	public static Block slab_brick1_diabaz;
	public static Block slab_brick2_diabaz;
	public static Block slab_big_brick_diabaz;
	public static Block stair_diabaz;
	public static Block stair_smooth_diabaz;
	public static Block stair_brick_diabaz;
	public static Block stair_big_brick_diabaz;
	public static Block carved_diabaz;
	public static Block pillar_diabaz;
	public static Block fence_diabaz;
	
	public static Block smooth_dolomit;
	public static Block brick1_dolomit;
	public static Block brick2_dolomit;
	public static Block big_brick_dolomit;
	public static Block slab_dolomit;
	public static Block slab_smooth_dolomit;
	public static Block slab_brick1_dolomit;
	public static Block slab_brick2_dolomit;
	public static Block slab_big_brick_dolomit;
	public static Block stair_dolomit;
	public static Block stair_smooth_dolomit;
	public static Block stair_brick_dolomit;
	public static Block stair_big_brick_dolomit;
	public static Block carved_dolomit;
	public static Block pillar_dolomit;
	public static Block fence_dolomit;
	
	public static Block smooth_pyroxenit;
	public static Block brick1_pyroxenit;
	public static Block brick2_pyroxenit;
	public static Block big_brick_pyroxenit;
	public static Block slab_pyroxenit;
	public static Block slab_smooth_pyroxenit;
	public static Block slab_brick1_pyroxenit;
	public static Block slab_brick2_pyroxenit;
	public static Block slab_big_brick_pyroxenit;
	public static Block stair_pyroxenit;
	public static Block stair_smooth_pyroxenit;
	public static Block stair_brick_pyroxenit;
	public static Block stair_big_brick_pyroxenit;
	public static Block carved_pyroxenit;
	public static Block pillar_pyroxenit;
	public static Block fence_pyroxenit;
	
	public static Block smooth_riolit;
	public static Block brick1_riolit;
	public static Block brick2_riolit;
	public static Block big_brick_riolit;
	public static Block slab_riolit;
	public static Block slab_smooth_riolit;
	public static Block slab_brick1_riolit;
	public static Block slab_brick2_riolit;
	public static Block slab_big_brick_riolit;
	public static Block stair_riolit;
	public static Block stair_smooth_riolit;
	public static Block stair_brick_riolit;
	public static Block stair_big_brick_riolit;
	public static Block carved_riolit;
	public static Block pillar_riolit;
	public static Block fence_riolit;
	
	public static Block smooth_kimberlit;
	public static Block brick1_kimberlit;
	public static Block brick2_kimberlit;
	public static Block big_brick_kimberlit;
	public static Block slab_kimberlit;
	public static Block slab_smooth_kimberlit;
	public static Block slab_brick1_kimberlit;
	public static Block slab_brick2_kimberlit;
	public static Block slab_big_brick_kimberlit;
	public static Block stair_kimberlit;
	public static Block stair_smooth_kimberlit;
	public static Block stair_brick_kimberlit;
	public static Block stair_big_brick_kimberlit;
	public static Block carved_kimberlit;
	public static Block pillar_kimberlit;
	public static Block fence_kimberlit;
	
	public static Block smooth_prizmarine;
	public static Block brick1_prizmarine;
	public static Block brick2_prizmarine;
	public static Block big_brick_prizmarine;
	public static Block slab_prizmarine;
	public static Block slab_smooth_prizmarine;
	public static Block slab_brick1_prizmarine;
	public static Block slab_brick2_prizmarine;
	public static Block slab_big_brick_prizmarine;
	public static Block stair_prizmarine;
	public static Block stair_smooth_prizmarine;
	public static Block stair_brick_prizmarine;
	public static Block stair_big_brick_prizmarine;
	public static Block carved_prizmarine;
	public static Block pillar_prizmarine;
	public static Block fence_prizmarine;
	
	public static Block smooth_carier;
	public static Block brick1_carier;
	public static Block brick2_carier;
	public static Block big_brick_carier;
	public static Block slab_carier;
	public static Block slab_smooth_carier;
	public static Block slab_brick1_carier;
	public static Block slab_brick2_carier;
	public static Block slab_big_brick_carier;
	public static Block stair_carier;
	public static Block stair_smooth_carier;
	public static Block stair_brick_carier;
	public static Block stair_big_brick_carier;
	public static Block carved_carier;
	public static Block pillar_carier;
	public static Block fence_carier;
	
	public static Block smooth_andesit;
	public static Block brick1_andesit;
	public static Block brick2_andesit;
	public static Block big_brick_andesit;
	public static Block slab_andesit;
	public static Block slab_smooth_andesit;
	public static Block slab_brick1_andesit;
	public static Block slab_brick2_andesit;
	public static Block slab_big_brick_andesit;
	public static Block stair_andesit;
	public static Block stair_smooth_andesit;
	public static Block stair_brick_andesit;
	public static Block stair_big_brick_andesit;
	public static Block carved_andesit;
	public static Block pillar_andesit;
	public static Block fence_andesit;
	
	public static Block smooth_granit;
	public static Block brick1_granit;
	public static Block brick2_granit;
	public static Block big_brick_granit;
	public static Block slab_granit;
	public static Block slab_smooth_granit;
	public static Block slab_brick1_granit;
	public static Block slab_brick2_granit;
	public static Block slab_big_brick_granit;
	public static Block stair_granit;
	public static Block stair_smooth_granit;
	public static Block stair_brick_granit;
	public static Block stair_big_brick_granit;
	public static Block carved_granit;
	public static Block pillar_granit;
	public static Block fence_granit;
	
	public static Block smooth_diorit;
	public static Block brick1_diorit;
	public static Block brick2_diorit;
	public static Block big_brick_diorit;
	public static Block slab_diorit;
	public static Block slab_smooth_diorit;
	public static Block slab_brick1_diorit;
	public static Block slab_brick2_diorit;
	public static Block slab_big_brick_diorit;
	public static Block stair_diorit;
	public static Block stair_smooth_diorit;
	public static Block stair_brick_diorit;
	public static Block stair_big_brick_diorit;
	public static Block carved_diorit;
	public static Block pillar_diorit;
	public static Block fence_diorit;
	
	public static Block smooth_marble;
	public static Block brick1_marble;
	public static Block brick2_marble;
	public static Block big_brick_marble;
	public static Block slab_marble;
	public static Block slab_smooth_marble;
	public static Block slab_brick1_marble;
	public static Block slab_brick2_marble;
	public static Block slab_big_brick_marble;
	public static Block stair_marble;
	public static Block stair_smooth_marble;
	public static Block stair_brick_marble;
	public static Block stair_big_brick_marble;
	public static Block carved_marble;
	public static Block pillar_marble;
	public static Block fence_marble;
	
	public static Block smooth_limestone;
	public static Block brick1_limestone;
	public static Block brick2_limestone;
	public static Block big_brick_limestone;
	public static Block slab_limestone;
	public static Block slab_smooth_limestone;
	public static Block slab_brick1_limestone;
	public static Block slab_brick2_limestone;
	public static Block slab_big_brick_limestone;
	public static Block stair_limestone;
	public static Block stair_smooth_limestone;
	public static Block stair_brick_limestone;
	public static Block stair_big_brick_limestone;
	public static Block carved_limestone;
	public static Block pillar_limestone;
	public static Block fence_limestone;
	
	
	public static Block wall_diabaz;
	public static Block wall_pyroxenit;
	public static Block wall_riolit;
	public static Block wall_kimberlit;
	public static Block wall_dolomit;
	public static Block wall_prizmarine;
	public static Block wall_andesit;
	public static Block wall_diorit;
	public static Block wall_granit;
	public static Block wall_limestone;
	public static Block wall_marble;
	public static Block wall_diabaz_brick2;
	public static Block wall_pyroxenit_brick2;
	public static Block wall_riolit_brick2;
	public static Block wall_kimberlit_brick2;
	public static Block wall_dolomit_brick2;
	public static Block wall_prizmarine_brick2;
	public static Block wall_andesit_brick2;
	public static Block wall_diorit_brick2;
	public static Block wall_granit_brick2;
	public static Block wall_limestone_brick2;
	public static Block wall_marble_brick2;
	
	
	@EventHandler
	public static void init()
	{
		
	      ametist_block = new CosmeticBlock("AmetistBlock", 5F, "manystones:AmetistBlock");
	      	  
	      	  GameRegistry.registerBlock(ametist_block, "AmetistBlock");
	      	  
		  smooth_diabaz = new CosmeticBlock("SmoothDiabaz", 2F, "manystones:SmoothDiabaz");
		  brick1_diabaz = new CosmeticBlock("Brick1Diabaz", 2F, "manystones:Brick1Diabaz");
		  brick2_diabaz = new CosmeticBlock("Brick2Diabaz", 2F, "manystones:Brick2Diabaz");
		  big_brick_diabaz = new CosmeticBlock("BigBrickDiabaz", 2F, "manystones:BigBrickDiabaz");
		  slab_diabaz = new CosmeticSlab("SlabDiabaz", 2F, "manystones:BlockDiabaz");
		  slab_smooth_diabaz = new CosmeticSlab("SlabSmoothDiabaz", 2F, "manystones:SmoothDiabaz");
		  slab_brick1_diabaz = new CosmeticSlab("SlabBrick1Diabaz", 2F, "manystones:Brick1Diabaz");
		  slab_brick2_diabaz = new CosmeticSlab("SlabBrick2Diabaz", 2F, "manystones:Brick2Diabaz");
		  slab_big_brick_diabaz = new CosmeticSlab("SlabBigBrickDiabaz", 2F, "manystones:BigBrickDiabaz");
		  stair_diabaz = new CosmeticStairs(WorldBlocks.diabaz, "StairDiabaz" , 2F, "manystones:StairDiabaz");
		  stair_smooth_diabaz = new CosmeticStairs(Decor.smooth_diabaz, "StairSmoothDiabaz" , 2F, "manystones:StairSmoothDiabaz");
		  stair_brick_diabaz = new CosmeticStairs(Decor.brick2_diabaz, "StairBrickDiabaz" , 2F, "manystones:StairBrickDiabaz");
		  stair_big_brick_diabaz = new CosmeticStairs(Decor.big_brick_diabaz, "StairBigBrickDiabaz" , 2F, "manystones:StairBigBrickDiabaz");
		  carved_diabaz = new CosmeticBlock("CarvedDiabaz", 2F, "manystones:CarvedDiabaz");
		  pillar_diabaz = new CosmeticPillar("PillarDiabaz", 2F, "manystones:PillarDiabaz");
		  fence_diabaz = new CosmeticFence(WorldBlocks.diabaz, "FenceDiabaz" , 2F, "manystones:BlockDiabaz");
		  wall_diabaz= new CosmeticWall(smooth_diabaz, "WallSmoothDiabaz", 2F, "manystones:SmoothDiabaz");
		  wall_diabaz_brick2= new CosmeticWall(brick2_diabaz, "WallBrick2Diabaz", 2F, "manystones:Brick2Diabaz");
		  
		  	 
			  GameRegistry.registerBlock(smooth_diabaz, "SmoothDiabaz");
			  GameRegistry.registerBlock(brick1_diabaz, "Brick1Diabaz");
			  GameRegistry.registerBlock(brick2_diabaz, "Brick2Diabaz");
			  GameRegistry.registerBlock(big_brick_diabaz, "BigBrickDiabaz");
			  GameRegistry.registerBlock(slab_diabaz, "SlabDiabaz");
			  GameRegistry.registerBlock(slab_smooth_diabaz, "SlabSmoothDiabaz");
			  GameRegistry.registerBlock( slab_brick1_diabaz, "SlabBrick1Diabaz");
			  GameRegistry.registerBlock( slab_brick2_diabaz, "SlabBrick2Diabaz");
			  GameRegistry.registerBlock(slab_big_brick_diabaz, "SlabBigBrickDiabaz");
			  GameRegistry.registerBlock(stair_diabaz, "StairDiabaz");
			  GameRegistry.registerBlock(stair_smooth_diabaz, "StairSmoothDiabaz");
			  GameRegistry.registerBlock(stair_brick_diabaz, "StairBrickDiabaz");
			  GameRegistry.registerBlock(stair_big_brick_diabaz, "StairBigBrickDiabaz");
			  GameRegistry.registerBlock(carved_diabaz, "CarvedDiabaz");
			  GameRegistry.registerBlock(pillar_diabaz, "PillarDiabaz");
			  GameRegistry.registerBlock(fence_diabaz, "FenceDiabaz");
			  GameRegistry.registerBlock(wall_diabaz, "SmoothWallDiabaz");
			  GameRegistry.registerBlock(wall_diabaz_brick2, "Brick2WallDiabaz");
			 
		  smooth_dolomit = new CosmeticBlock("SmoothDolomit", 2F, "manystones:SmoothDolomit");
		  brick1_dolomit = new CosmeticBlock("Brick1Dolomit", 2F, "manystones:Brick1Dolomit");
		  brick2_dolomit = new CosmeticBlock("Brick2Dolomit", 2F, "manystones:Brick2Dolomit");
		  big_brick_dolomit = new CosmeticBlock("BigBrickDolomit", 2F, "manystones:BigBrickDolomit");
		  slab_dolomit = new CosmeticSlab("SlabDolomit", 2F, "manystones:BlockDolomit");
		  slab_smooth_dolomit = new CosmeticSlab("SlabSmoothDolomit", 2F, "manystones:SmoothDolomit");
		  slab_brick1_dolomit = new CosmeticSlab("SlabBrick1Dolomit", 2F, "manystones:Brick1Dolomit");
		  slab_brick2_dolomit = new CosmeticSlab("SlabBrick2Dolomit", 2F, "manystones:Brick2Dolomit");
		  slab_big_brick_dolomit = new CosmeticSlab("SlabBigBrickDolomit", 2F, "manystones:BigBrickDolomit");
		  stair_dolomit = new CosmeticStairs(WorldBlocks.dolomit, "StairDolomit" , 2F, "manystones:StairDolomit");
		  stair_smooth_dolomit = new CosmeticStairs(Decor.smooth_dolomit, "StairSmoothDolomit" , 2F, "manystones:StairSmoothDolomit");
		  stair_brick_dolomit = new CosmeticStairs(Decor.brick2_dolomit, "StairBrickDolomit" , 2F, "manystones:StairBrickDolomit");
		  stair_big_brick_dolomit = new CosmeticStairs(Decor.big_brick_dolomit, "StairBigBrickDolomit" , 2F, "manystones:StairBigBrickDolomit");
		  carved_dolomit = new CosmeticBlock("CarvedDolomit", 2F, "manystones:CarvedDolomit");
		  pillar_dolomit = new CosmeticPillar("PillarDolomit", 2F, "manystones:PillarDolomit");
		  fence_dolomit = new CosmeticFence(WorldBlocks.dolomit, "FenceDolomit" , 2F, "manystones:BlockDolomit");
		  wall_dolomit= new CosmeticWall(smooth_dolomit, "WallSmoothKimberlit", 2F, "manystones:SmoothDolomit");
		  wall_dolomit_brick2= new CosmeticWall(brick2_dolomit, "WallBrick2Dolomit", 2F, "manystones:Brick2Dolomit");
		  
			  GameRegistry.registerBlock(smooth_dolomit, "SmoothDolomit");
			  GameRegistry.registerBlock(brick1_dolomit, "Brick1Dolomit");
			  GameRegistry.registerBlock(brick2_dolomit, "Brick2Dolomit");
			  GameRegistry.registerBlock(big_brick_dolomit, "BigBrickDolomit");
			  GameRegistry.registerBlock(slab_dolomit, "SlabDolomit");
			  GameRegistry.registerBlock(slab_smooth_dolomit, "SlabSmoothDolomit");
			  GameRegistry.registerBlock( slab_brick1_dolomit, "SlabBric1kDolomit");
			  GameRegistry.registerBlock( slab_brick2_dolomit, "SlabBrick2Dolomit");
			  GameRegistry.registerBlock(slab_big_brick_dolomit, "SlabBigBrickDolomit");
			  GameRegistry.registerBlock(stair_dolomit, "StairDolomit");
			  GameRegistry.registerBlock(stair_smooth_dolomit, "StairSmoothDolomit");
			  GameRegistry.registerBlock(stair_brick_dolomit, "StairBrickDolomit");
			  GameRegistry.registerBlock(stair_big_brick_dolomit, "StairBigBrickDolomit");
			  GameRegistry.registerBlock(carved_dolomit, "CarvedDolomit");
			  GameRegistry.registerBlock(pillar_dolomit, "PillarDolomit");
			  GameRegistry.registerBlock(fence_dolomit, "FenceDolomit");
			  GameRegistry.registerBlock(wall_dolomit, "SmoothWallDolomit");
			  GameRegistry.registerBlock(wall_dolomit_brick2, "Brick2WallDolomit");
			 
		  smooth_riolit = new CosmeticBlock("SmoothRiolit", 2F, "manystones:SmoothRiolit");
		  brick1_riolit = new CosmeticBlock("Brick1Riolit", 2F, "manystones:Brick1Riolit");
		  brick2_riolit = new CosmeticBlock("Brick2Riolit", 2F, "manystones:Brick2Riolit");
		  big_brick_riolit = new CosmeticBlock("BigBrickRiolit", 2F, "manystones:BigBrickRiolit");
		  slab_riolit = new CosmeticSlab("SlabRiolit", 2F, "manystones:BlockRiolit");
		  slab_smooth_riolit = new CosmeticSlab("SlabSmoothRiolit", 2F, "manystones:SmoothRiolit");
		  slab_brick1_riolit = new CosmeticSlab("SlabBrick1Riolit", 2F, "manystones:Brick1Riolit");
		  slab_brick2_riolit = new CosmeticSlab("SlabBrick2Riolit", 2F, "manystones:Brick2Riolit");
		  slab_big_brick_riolit = new CosmeticSlab("SlabBigBrickRiolit", 2F, "manystones:BigBrickRiolit");
		  stair_riolit = new CosmeticStairs(WorldBlocks.riolit, "StairRiolit" , 2F, "manystones:StairRiolit");
		  stair_smooth_riolit = new CosmeticStairs(Decor.smooth_riolit, "StairSmoothRiolit" , 2F, "manystones:StairSmoothRiolit");
		  stair_brick_riolit = new CosmeticStairs(Decor.brick2_riolit, "StairBrickRiolit" , 2F, "manystones:StairBrickRiolit");
		  stair_big_brick_riolit = new CosmeticStairs(Decor.big_brick_riolit, "StairBigBrickRiolit" , 2F, "manystones:StairBigBrickRiolit");
		  carved_riolit = new CosmeticBlock("CarvedRiolit", 2F, "manystones:CarvedRiolit");
		  pillar_riolit = new CosmeticPillar("PillarRiolit", 2F, "manystones:PillarRiolit");
		  fence_riolit = new CosmeticFence(WorldBlocks.riolit, "FenceRiolit" , 2F, "manystones:BlockRiolit");
		  wall_riolit= new CosmeticWall(smooth_riolit, "WallSmoothRiolit", 2F, "manystones:SmoothRiolit");
		  wall_riolit_brick2= new CosmeticWall(brick2_riolit, "WallBrick2Riolit", 2F, "manystones:Brick2Riolit");
		  
			  GameRegistry.registerBlock(smooth_riolit, "SmoothRiolit");
			  GameRegistry.registerBlock(brick1_riolit, "Brick1Riolit");
			  GameRegistry.registerBlock(brick2_riolit, "Brick2Riolit");
			  GameRegistry.registerBlock(big_brick_riolit, "BigBrickRiolit");
			  GameRegistry.registerBlock(slab_riolit, "BlockRiolit");
			  GameRegistry.registerBlock(slab_smooth_riolit, "BlockSmoothRiolit");
			  GameRegistry.registerBlock( slab_brick1_riolit, "BlockBrick1Riolit");
			  GameRegistry.registerBlock( slab_brick2_riolit, "BlockBrick2Riolit");
			  GameRegistry.registerBlock(slab_big_brick_riolit, "BlockBigBrickRiolit");
			  GameRegistry.registerBlock(stair_riolit, "StairRiolit");
			  GameRegistry.registerBlock(stair_smooth_riolit, "StairSmoothRiolit");
			  GameRegistry.registerBlock(stair_brick_riolit, "StairBrickRiolit");
			  GameRegistry.registerBlock(stair_big_brick_riolit, "StairBigBrickRiolit");
			  GameRegistry.registerBlock(carved_riolit, "CarvedRiolit");
			  GameRegistry.registerBlock(pillar_riolit, "PillarRiolit");
			  GameRegistry.registerBlock(fence_riolit, "FenceRiolit");
			  GameRegistry.registerBlock(wall_riolit, "SmoothWallRiolit");
			  GameRegistry.registerBlock(wall_riolit_brick2, "Brick2WallRiolit");
			 
		  smooth_kimberlit = new CosmeticBlock("SmoothKimberlit", 2F, "manystones:SmoothKimberlit");
		  brick1_kimberlit = new CosmeticBlock("Brick1Kimberlit", 2F, "manystones:Brick1Kimberlit");
		  brick2_kimberlit = new CosmeticBlock("Brick2Kimberlit", 2F, "manystones:Brick2Kimberlit");
		  big_brick_kimberlit = new CosmeticBlock("BigBrickKimberlit", 2F, "manystones:BigBrickKimberlit");
		  slab_kimberlit = new CosmeticSlab("SlabKimberlit", 2F, "manystones:BlockKimberlit");
		  slab_smooth_kimberlit = new CosmeticSlab("SlabSmoothKimberlit", 2F, "manystones:SmoothKimberlit");
		  slab_brick1_kimberlit = new CosmeticSlab("SlabBrick1Kimberlit", 2F, "manystones:Brick1Kimberlit");
		  slab_brick2_kimberlit = new CosmeticSlab("SlabBrick2Kimberlit", 2F, "manystones:Brick2Kimberlit");
		  slab_big_brick_kimberlit = new CosmeticSlab("SlabBigBrickKimberlit", 2F, "manystones:BigBrickKimberlit");
		  stair_kimberlit = new CosmeticStairs(WorldBlocks.kimberlit, "StairKimberlit" , 2F, "manystones:StairKimberlit");
		  stair_smooth_kimberlit = new CosmeticStairs(Decor.smooth_kimberlit, "StairSmoothKimberlit" , 2F, "manystones:StairSmoothKimberlit");
		  stair_brick_kimberlit = new CosmeticStairs(Decor.brick2_kimberlit, "StairBrickKimberlit" , 2F, "manystones:StairBrickKimberlit");
		  stair_big_brick_kimberlit = new CosmeticStairs(Decor.big_brick_kimberlit, "StairBigBrickKimberlit" , 2F, "manystones:StairBigBrickKimberlit");
		  carved_kimberlit = new CosmeticBlock("CarvedKimberlit", 2F, "manystones:CarvedKimberlit");
		  pillar_kimberlit = new CosmeticPillar("PillarKimberlit", 2F, "manystones:PillarKimberlit");
		  fence_kimberlit = new CosmeticFence(WorldBlocks.kimberlit, "FenceKimberlit" , 2F, "manystones:BlockKimberlit");
		  wall_kimberlit= new CosmeticWall(smooth_kimberlit, "Wall", 2F, "manystones:SmoothKimberlit");
		  wall_kimberlit_brick2= new CosmeticWall(brick2_kimberlit, "WallBrick2Kimberlit", 2F, "manystones:Brick2Kimberlit");
		  
			  GameRegistry.registerBlock(smooth_kimberlit, "SmoothKimberlit");
			  GameRegistry.registerBlock(brick1_kimberlit, "Brick1Kimberlit");
			  GameRegistry.registerBlock(brick2_kimberlit, "Brick2Kimberlit");
			  GameRegistry.registerBlock(big_brick_kimberlit, "BigBrickKimberlit");
			  GameRegistry.registerBlock(slab_kimberlit, "SlabKimberlit");
			  GameRegistry.registerBlock(slab_smooth_kimberlit, "SlabSmoothKimberlit");
			  GameRegistry.registerBlock(slab_brick1_kimberlit, "SlabBrick1Kimberlit");
			  GameRegistry.registerBlock(slab_brick2_kimberlit, "SlabBrick2Kimberlit");
			  GameRegistry.registerBlock(slab_big_brick_kimberlit, "SlabBigBrickKimberlit");
			  GameRegistry.registerBlock(stair_kimberlit, "StairKimberlit");
			  GameRegistry.registerBlock(stair_smooth_kimberlit, "StairSmoothKimberlit");
			  GameRegistry.registerBlock(stair_brick_kimberlit, "StairBrickKimberlit");
			  GameRegistry.registerBlock(stair_big_brick_kimberlit, "StairBigBrickKimberlit");
			  GameRegistry.registerBlock(carved_kimberlit, "CarvedKimberlit");
			  GameRegistry.registerBlock(pillar_kimberlit, "PillarKimberlit");
			  GameRegistry.registerBlock(fence_kimberlit, "FenceKimberlit");
			  GameRegistry.registerBlock(wall_kimberlit, "SmoothWallKimberlit");
			  GameRegistry.registerBlock(wall_kimberlit_brick2, "Brick2WallKimberlit");
			 
		  smooth_pyroxenit = new CosmeticBlock("SmoothPyroxenit", 2F, "manystones:SmoothPyroxenit");
		  brick1_pyroxenit = new CosmeticBlock("Brick1Pyroxenit", 2F, "manystones:Brick1Pyroxenit");
		  brick2_pyroxenit = new CosmeticBlock("Brick2Pyroxenit", 2F, "manystones:Brick2Pyroxenit");
		  big_brick_pyroxenit = new CosmeticBlock("BigBrickPyroxenit", 2F, "manystones:BigBrickPyroxenit");
		  slab_pyroxenit = new CosmeticSlab("SlabPyroxenit", 2F, "manystones:BlockPyroxenit");
		  slab_smooth_pyroxenit = new CosmeticSlab("SlabSmoothPyroxenit", 2F, "manystones:SmoothPyroxenit");
		  slab_brick1_pyroxenit = new CosmeticSlab("SlabBrick1Pyroxenit", 2F, "manystones:Brick1Pyroxenit");
		  slab_brick2_pyroxenit = new CosmeticSlab("SlabBrick2Pyroxenit", 2F, "manystones:Brick2Pyroxenit");
		  slab_big_brick_pyroxenit = new CosmeticSlab("SlabBigBrickPyroxenit", 2F, "manystones:BigBrickPyroxenit");
		  stair_pyroxenit = new CosmeticStairs(WorldBlocks.pyroxenit, "StairPyroxenit" , 2F, "manystones:StairPyroxenit");
		  stair_smooth_pyroxenit = new CosmeticStairs(Decor.smooth_pyroxenit, "StairSmoothPyroxenit" , 2F, "manystones:StairSmoothPyroxenit");
		  stair_brick_pyroxenit = new CosmeticStairs(Decor.brick2_pyroxenit, "StairBrickPyroxenit" , 2F, "manystones:StairBrickPyroxenit");
		  stair_big_brick_pyroxenit = new CosmeticStairs(Decor.big_brick_pyroxenit, "StairBigBrickPyroxenit" , 2F, "manystones:StairBigBrickPyroxenit");
		  carved_pyroxenit = new CosmeticBlock("CarvedPyroxenit", 2F, "manystones:CarvedPyroxenit");
		  pillar_pyroxenit = new CosmeticPillar("PillarPyroxenit", 2F, "manystones:PillarPyroxenit");
		  fence_pyroxenit = new CosmeticFence(WorldBlocks.pyroxenit, "FencePyroxenit" , 2F, "manystones:BlockPyroxenit");
		  wall_pyroxenit= new CosmeticWall(smooth_pyroxenit, "WallSmoothPyroxenit", 2F, "manystones:SmoothPyroxenit");
		  wall_pyroxenit_brick2= new CosmeticWall(brick2_pyroxenit, "WallBrick2Pyroxenit", 2F, "manystones:Brick2Pyroxenit");
		  
			  GameRegistry.registerBlock(smooth_pyroxenit, "SmoothPyroxenit");
			  GameRegistry.registerBlock(brick1_pyroxenit, "Brick1Pyroxenit");
			  GameRegistry.registerBlock(brick2_pyroxenit, "Brick2Pyroxenit");
			  GameRegistry.registerBlock(big_brick_pyroxenit, "BigBrickPyroxenit");
			  GameRegistry.registerBlock(slab_pyroxenit, "SlabPyroxenit");
			  GameRegistry.registerBlock(slab_smooth_pyroxenit, "SlabSmoothPyroxenit");
			  GameRegistry.registerBlock(slab_brick1_pyroxenit, "SlabBrick1Pyroxenit");
			  GameRegistry.registerBlock(slab_brick2_pyroxenit, "SlabBrick2Pyroxenit");
			  GameRegistry.registerBlock(slab_big_brick_pyroxenit, "SlabBigBrickPyroxenit");
			  GameRegistry.registerBlock(stair_pyroxenit, "StairPyroxenit");
			  GameRegistry.registerBlock(stair_smooth_pyroxenit, "StairSmoothPyroxenit");
			  GameRegistry.registerBlock(stair_brick_pyroxenit, "StairBrickPyroxenit");
			  GameRegistry.registerBlock(stair_big_brick_pyroxenit, "StairBigBrickPyroxenit");
			  GameRegistry.registerBlock(carved_pyroxenit, "CarvedPyroxenit");
			  GameRegistry.registerBlock(pillar_pyroxenit, "PillarPyroxenit");
			  GameRegistry.registerBlock(fence_pyroxenit, "FencePyroxenit");
			  GameRegistry.registerBlock(wall_pyroxenit, "SmoothWallPyroxenit");
			  GameRegistry.registerBlock(wall_pyroxenit_brick2, "Brick2WallPyroxenit");
		  
		  smooth_prizmarine = new CosmeticBlock("SmoothPrizmarine", 2F, "manystones:SmoothPrizmarine");
		  brick1_prizmarine = new CosmeticBlock("Brick1Prizmarine", 2F, "manystones:Brick1Prizmarine");
		  brick2_prizmarine = new CosmeticBlock("Brick2Prizmarine", 2F, "manystones:Brick2Prizmarine");
		  big_brick_prizmarine = new CosmeticBlock("BigBrickPrizmarine", 2F, "manystones:BigBrickPrizmarine");
		  slab_prizmarine = new CosmeticSlab("SlabPrizmarine", 2F, "manystones:BlockPrizmarine");
		  slab_smooth_prizmarine = new CosmeticSlab("SlabSmoothPrizmarine", 2F, "manystones:SmoothPrizmarine");
		  slab_brick1_prizmarine = new CosmeticSlab("SlabBrick1Prizmarine", 2F, "manystones:Brick1Prizmarine");
		  slab_brick2_prizmarine = new CosmeticSlab("SlabBrick2Prizmarine", 2F, "manystones:Brick2Prizmarine");
		  slab_big_brick_prizmarine = new CosmeticSlab("SlabBigBrickPrizmarine", 2F, "manystones:BigBrickPrizmarine");
		  stair_prizmarine = new CosmeticStairs(WorldBlocks.prizmarine, "StairPrizmarine" , 2F, "manystones:StairPrizmarine");
		  stair_smooth_prizmarine = new CosmeticStairs(Decor.smooth_prizmarine, "StairSmoothPrizmarine" , 2F, "manystones:StairSmoothPrizmarine");
		  stair_brick_prizmarine = new CosmeticStairs(Decor.brick2_prizmarine, "StairBrickPrizmarine" , 2F, "manystones:StairBrickPrizmarine");
		  stair_big_brick_prizmarine = new CosmeticStairs(Decor.big_brick_prizmarine, "StairBigBrickPrizmarine" , 2F, "manystones:StairBigBrickPrizmarine");
		  carved_prizmarine = new CosmeticBlock("CarvedPrizmarine", 2F, "manystones:CarvedPrizmarine");
		  pillar_prizmarine = new CosmeticPillar("PillarPrizmarine", 2F, "manystones:PillarPrizmarine");
		  fence_prizmarine = new CosmeticFence(WorldBlocks.prizmarine, "FencePrizmarine" , 2F, "manystones:BlockPrizmarine");
		  wall_prizmarine= new CosmeticWall(smooth_prizmarine, "WallSmoothPrizmarine", 2F, "manystones:SmoothPrizmarine");
		  wall_prizmarine_brick2= new CosmeticWall(brick2_prizmarine, "WallBrick2Prizmarine", 2F, "manystones:Brick2Prizmarine");
		  
			  GameRegistry.registerBlock(smooth_prizmarine, "SmoothPrizmarine");
			  GameRegistry.registerBlock(brick1_prizmarine, "Brick1Prizmarine");
			  GameRegistry.registerBlock(brick2_prizmarine, "Brick2Prizmarine");
			  GameRegistry.registerBlock(big_brick_prizmarine, "BigBrickPrizmarine");
			  GameRegistry.registerBlock(slab_prizmarine, "SlabPrizmarine");
			  GameRegistry.registerBlock(slab_smooth_prizmarine, "SlabSmoothPrizmarine");
			  GameRegistry.registerBlock( slab_brick1_prizmarine, "SlabBrick1Prizmarine");
			  GameRegistry.registerBlock( slab_brick2_prizmarine, "SlabBrick2Prizmarine");
			  GameRegistry.registerBlock(slab_big_brick_prizmarine, "SlabBigBrickPrizmarine");
			  GameRegistry.registerBlock(stair_prizmarine, "StairPrizmarine");
			  GameRegistry.registerBlock(stair_smooth_prizmarine, "StairSmoothPrizmarine");
			  GameRegistry.registerBlock(stair_brick_prizmarine, "StairBrickPrizmarine");
			  GameRegistry.registerBlock(stair_big_brick_prizmarine, "StairBigBrickPrizmarine");
			  GameRegistry.registerBlock(carved_prizmarine, "CarvedPrizmarine");
			  GameRegistry.registerBlock(pillar_prizmarine, "PillarPrizmarine");
			  GameRegistry.registerBlock(fence_prizmarine, "FencePrizmarine");
			  GameRegistry.registerBlock(wall_prizmarine, "SmoothWallPrizmarine");
			  GameRegistry.registerBlock(wall_prizmarine_brick2, "Brick2WallPrizmarine");

	      	  
			  smooth_andesit = new CosmeticBlock("SmoothAndesit", 2F, "manystones:SmoothAndesit");
			  brick1_andesit = new CosmeticBlock("Brick1Andesit", 2F, "manystones:Brick1Andesit");
			  brick2_andesit = new CosmeticBlock("Brick2Andesit", 2F, "manystones:Brick2Andesit");
			  big_brick_andesit = new CosmeticBlock("BigBrickAndesit", 2F, "manystones:BigBrickAndesit");
			  slab_andesit = new CosmeticSlab("SlabAndesit", 2F, "manystones:BlockAndesit");
			  slab_smooth_andesit = new CosmeticSlab("SlabSmoothAndesit", 2F, "manystones:SmoothAndesit");
			  slab_brick1_andesit = new CosmeticSlab("SlabBrick1Andesit", 2F, "manystones:Brick1Andesit");
			  slab_brick2_andesit = new CosmeticSlab("SlabBrick2Andesit", 2F, "manystones:Brick2Andesit");
			  slab_big_brick_andesit = new CosmeticSlab("SlabBigBrickAndesit", 2F, "manystones:BigBrickAndesit");
			  stair_andesit = new CosmeticStairs(WorldBlocks.andesit, "StairAndesit" , 2F, "manystones:StairAndesit");
			  stair_smooth_andesit = new CosmeticStairs(Decor.smooth_andesit, "StairSmoothAndesit" , 2F, "manystones:StairSmoothAndesit");
			  stair_brick_andesit = new CosmeticStairs(Decor.brick2_andesit, "StairBrickAndesit" , 2F, "manystones:StairBrickAndesit");
			  stair_big_brick_andesit = new CosmeticStairs(Decor.big_brick_andesit, "StairBigBrickAndesit" , 2F, "manystones:StairBigBrickAndesit");
			  carved_andesit = new CosmeticBlock("CarvedAndesit", 2F, "manystones:CarvedAndesit");
			  pillar_andesit = new CosmeticPillar("PillarAndesit", 2F, "manystones:PillarAndesit");
			  fence_andesit = new CosmeticFence(WorldBlocks.andesit, "FenceAndesit" , 2F, "manystones:BlockAndesit");
			  wall_andesit= new CosmeticWall(smooth_andesit, "WallSmoothAndesit", 2F, "manystones:SmoothAndesit");
			  wall_andesit_brick2= new CosmeticWall(brick2_andesit, "WallBrick2Andesit", 2F, "manystones:Brick2Andesit");
			  
			  	 
				  GameRegistry.registerBlock(smooth_andesit, "SmoothAndesit");
				  GameRegistry.registerBlock(brick1_andesit, "Brick1Andesit");
				  GameRegistry.registerBlock(brick2_andesit, "Brick2Andesit");
				  GameRegistry.registerBlock(big_brick_andesit, "BigBrickAndesit");
				  GameRegistry.registerBlock(slab_andesit, "SlabAndesit");
				  GameRegistry.registerBlock(slab_smooth_andesit, "SlabSmoothAndesit");
				  GameRegistry.registerBlock( slab_brick1_andesit, "SlabBrick1Andesit");
				  GameRegistry.registerBlock( slab_brick2_andesit, "SlabBrick2Andesit");
				  GameRegistry.registerBlock(slab_big_brick_andesit, "SlabBigBrickAndesit");
				  GameRegistry.registerBlock(stair_andesit, "StairAndesit");
				  GameRegistry.registerBlock(stair_smooth_andesit, "StairSmoothAndesit");
				  GameRegistry.registerBlock(stair_brick_andesit, "StairBrickAndesit");
				  GameRegistry.registerBlock(stair_big_brick_andesit, "StairBigBrickAndesit");
				  GameRegistry.registerBlock(carved_andesit, "CarvedAndesit");
				  GameRegistry.registerBlock(pillar_andesit, "PillarAndesit");
				  GameRegistry.registerBlock(fence_andesit, "FenceAndesit");
				  GameRegistry.registerBlock(wall_andesit, "SmoothWallAndesit");
				  GameRegistry.registerBlock(wall_andesit_brick2, "Brick2WallAndesit");
				 
			  smooth_granit = new CosmeticBlock("SmoothGranit", 2F, "manystones:SmoothGranit");
			  brick1_granit = new CosmeticBlock("Brick1Granit", 2F, "manystones:Brick1Granit");
			  brick2_granit = new CosmeticBlock("Brick2Granit", 2F, "manystones:Brick2Granit");
			  big_brick_granit = new CosmeticBlock("BigBrickGranit", 2F, "manystones:BigBrickGranit");
			  slab_granit = new CosmeticSlab("SlabGranit", 2F, "manystones:BlockGranit");
			  slab_smooth_granit = new CosmeticSlab("SlabSmoothGranit", 2F, "manystones:SmoothGranit");
			  slab_brick1_granit = new CosmeticSlab("SlabBrick1Granit", 2F, "manystones:Brick1Granit");
			  slab_brick2_granit = new CosmeticSlab("SlabBrick2Granit", 2F, "manystones:Brick2Granit");
			  slab_big_brick_granit = new CosmeticSlab("SlabBigBrickGranit", 2F, "manystones:BigBrickGranit");
			  stair_granit = new CosmeticStairs(WorldBlocks.granit, "StairGranit" , 2F, "manystones:StairGranit");
			  stair_smooth_granit = new CosmeticStairs(Decor.smooth_granit, "StairSmoothGranit" , 2F, "manystones:StairSmoothGranit");
			  stair_brick_granit = new CosmeticStairs(Decor.brick2_granit, "StairBrickGranit" , 2F, "manystones:StairBrickGranit");
			  stair_big_brick_granit = new CosmeticStairs(Decor.big_brick_granit, "StairBigBrickGranit" , 2F, "manystones:StairBigBrickGranit");
			  carved_granit = new CosmeticBlock("CarvedGranit", 2F, "manystones:CarvedGranit");
			  pillar_granit = new CosmeticPillar("PillarGranit", 2F, "manystones:PillarGranit");
			  fence_granit = new CosmeticFence(WorldBlocks.granit, "FenceGranit" , 2F, "manystones:BlockGranit");
			  wall_granit= new CosmeticWall(smooth_granit, "WallSmoothKimberlit", 2F, "manystones:SmoothGranit");
			  wall_granit_brick2= new CosmeticWall(brick2_granit, "WallBrick2Granit", 2F, "manystones:Brick2Granit");
			  
				  GameRegistry.registerBlock(smooth_granit, "SmoothGranit");
				  GameRegistry.registerBlock(brick1_granit, "Brick1Granit");
				  GameRegistry.registerBlock(brick2_granit, "Brick2Granit");
				  GameRegistry.registerBlock(big_brick_granit, "BigBrickGranit");
				  GameRegistry.registerBlock(slab_granit, "SlabGranit");
				  GameRegistry.registerBlock(slab_smooth_granit, "SlabSmoothGranit");
				  GameRegistry.registerBlock( slab_brick1_granit, "SlabBric1kGranit");
				  GameRegistry.registerBlock( slab_brick2_granit, "SlabBrick2Granit");
				  GameRegistry.registerBlock(slab_big_brick_granit, "SlabBigBrickGranit");
				  GameRegistry.registerBlock(stair_granit, "StairGranit");
				  GameRegistry.registerBlock(stair_smooth_granit, "StairSmoothGranit");
				  GameRegistry.registerBlock(stair_brick_granit, "StairBrickGranit");
				  GameRegistry.registerBlock(stair_big_brick_granit, "StairBigBrickGranit");
				  GameRegistry.registerBlock(carved_granit, "CarvedGranit");
				  GameRegistry.registerBlock(pillar_granit, "PillarGranit");
				  GameRegistry.registerBlock(fence_granit, "FenceGranit");
				  GameRegistry.registerBlock(wall_granit, "SmoothWallGranit");
				  GameRegistry.registerBlock(wall_granit_brick2, "Brick2WallGranit");
				 
			  smooth_diorit = new CosmeticBlock("SmoothDiorit", 2F, "manystones:SmoothDiorit");
			  brick1_diorit = new CosmeticBlock("Brick1Diorit", 2F, "manystones:Brick1Diorit");
			  brick2_diorit = new CosmeticBlock("Brick2Diorit", 2F, "manystones:Brick2Diorit");
			  big_brick_diorit = new CosmeticBlock("BigBrickDiorit", 2F, "manystones:BigBrickDiorit");
			  slab_diorit = new CosmeticSlab("SlabDiorit", 2F, "manystones:BlockDiorit");
			  slab_smooth_diorit = new CosmeticSlab("SlabSmoothDiorit", 2F, "manystones:SmoothDiorit");
			  slab_brick1_diorit = new CosmeticSlab("SlabBrick1Diorit", 2F, "manystones:Brick1Diorit");
			  slab_brick2_diorit = new CosmeticSlab("SlabBrick2Diorit", 2F, "manystones:Brick2Diorit");
			  slab_big_brick_diorit = new CosmeticSlab("SlabBigBrickDiorit", 2F, "manystones:BigBrickDiorit");
			  stair_diorit = new CosmeticStairs(WorldBlocks.diorit, "StairDiorit" , 2F, "manystones:StairDiorit");
			  stair_smooth_diorit = new CosmeticStairs(Decor.smooth_diorit, "StairSmoothDiorit" , 2F, "manystones:StairSmoothDiorit");
			  stair_brick_diorit = new CosmeticStairs(Decor.brick2_diorit, "StairBrickDiorit" , 2F, "manystones:StairBrickDiorit");
			  stair_big_brick_diorit = new CosmeticStairs(Decor.big_brick_diorit, "StairBigBrickDiorit" , 2F, "manystones:StairBigBrickDiorit");
			  carved_diorit = new CosmeticBlock("CarvedDiorit", 2F, "manystones:CarvedDiorit");
			  pillar_diorit = new CosmeticPillar("PillarDiorit", 2F, "manystones:PillarDiorit");
			  fence_diorit = new CosmeticFence(WorldBlocks.diorit, "FenceDiorit" , 2F, "manystones:BlockDiorit");
			  wall_diorit= new CosmeticWall(smooth_diorit, "WallSmoothDiorit", 2F, "manystones:SmoothDiorit");
			  wall_diorit_brick2= new CosmeticWall(brick2_diorit, "WallBrick2Diorit", 2F, "manystones:Brick2Diorit");
			  
				  GameRegistry.registerBlock(smooth_diorit, "SmoothDiorit");
				  GameRegistry.registerBlock(brick1_diorit, "Brick1Diorit");
				  GameRegistry.registerBlock(brick2_diorit, "Brick2Diorit");
				  GameRegistry.registerBlock(big_brick_diorit, "BigBrickDiorit");
				  GameRegistry.registerBlock(slab_diorit, "BlockDiorit");
				  GameRegistry.registerBlock(slab_smooth_diorit, "BlockSmoothDiorit");
				  GameRegistry.registerBlock( slab_brick1_diorit, "BlockBrick1Diorit");
				  GameRegistry.registerBlock( slab_brick2_diorit, "BlockBrick2Diorit");
				  GameRegistry.registerBlock(slab_big_brick_diorit, "BlockBigBrickDiorit");
				  GameRegistry.registerBlock(stair_diorit, "StairDiorit");
				  GameRegistry.registerBlock(stair_smooth_diorit, "StairSmoothDiorit");
				  GameRegistry.registerBlock(stair_brick_diorit, "StairBrickDiorit");
				  GameRegistry.registerBlock(stair_big_brick_diorit, "StairBigBrickDiorit");
				  GameRegistry.registerBlock(carved_diorit, "CarvedDiorit");
				  GameRegistry.registerBlock(pillar_diorit, "PillarDiorit");
				  GameRegistry.registerBlock(fence_diorit, "FenceDiorit");
				  GameRegistry.registerBlock(wall_diorit, "SmoothWallDiorit");
				  GameRegistry.registerBlock(wall_diorit_brick2, "Brick2WallDiorit");
				 
			  smooth_limestone = new CosmeticBlock("SmoothLimestone", 2F, "manystones:SmoothLimestone");
			  brick1_limestone = new CosmeticBlock("Brick1Limestone", 2F, "manystones:Brick1Limestone");
			  brick2_limestone = new CosmeticBlock("Brick2Limestone", 2F, "manystones:Brick2Limestone");
			  big_brick_limestone = new CosmeticBlock("BigBrickLimestone", 2F, "manystones:BigBrickLimestone");
			  slab_limestone = new CosmeticSlab("SlabLimestone", 2F, "manystones:BlockLimestone");
			  slab_smooth_limestone = new CosmeticSlab("SlabSmoothLimestone", 2F, "manystones:SmoothLimestone");
			  slab_brick1_limestone = new CosmeticSlab("SlabBrick1Limestone", 2F, "manystones:Brick1Limestone");
			  slab_brick2_limestone = new CosmeticSlab("SlabBrick2Limestone", 2F, "manystones:Brick2Limestone");
			  slab_big_brick_limestone = new CosmeticSlab("SlabBigBrickLimestone", 2F, "manystones:BigBrickLimestone");
			  stair_limestone = new CosmeticStairs(WorldBlocks.limestone, "StairLimestone" , 2F, "manystones:StairLimestone");
			  stair_smooth_limestone = new CosmeticStairs(Decor.smooth_limestone, "StairSmoothLimestone" , 2F, "manystones:StairSmoothLimestone");
			  stair_brick_limestone = new CosmeticStairs(Decor.brick2_limestone, "StairBrickLimestone" , 2F, "manystones:StairBrickLimestone");
			  stair_big_brick_limestone = new CosmeticStairs(Decor.big_brick_limestone, "StairBigBrickLimestone" , 2F, "manystones:StairBigBrickLimestone");
			  carved_limestone = new CosmeticBlock("CarvedLimestone", 2F, "manystones:CarvedLimestone");
			  pillar_limestone = new CosmeticPillar("PillarLimestone", 2F, "manystones:PillarLimestone");
			  fence_limestone = new CosmeticFence(WorldBlocks.limestone, "FenceLimestone" , 2F, "manystones:BlockLimestone");
			  wall_limestone= new CosmeticWall(smooth_limestone, "WallSmoothLimestone", 2F, "manystones:SmoothLimestone");
			  wall_limestone_brick2= new CosmeticWall(brick2_limestone, "WallBrick2Limestone", 2F, "manystones:Brick2Limestone");
			  
				  GameRegistry.registerBlock(smooth_limestone, "SmoothLimestone");
				  GameRegistry.registerBlock(brick1_limestone, "Brick1Limestone");
				  GameRegistry.registerBlock(brick2_limestone, "Brick2Limestone");
				  GameRegistry.registerBlock(big_brick_limestone, "BigBrickLimestone");
				  GameRegistry.registerBlock(slab_limestone, "SlabLimestone");
				  GameRegistry.registerBlock(slab_smooth_limestone, "SlabSmoothLimestone");
				  GameRegistry.registerBlock(slab_brick1_limestone, "SlabBrick1Limestone");
				  GameRegistry.registerBlock(slab_brick2_limestone, "SlabBrick2Limestone");
				  GameRegistry.registerBlock(slab_big_brick_limestone, "SlabBigBrickLimestone");
				  GameRegistry.registerBlock(stair_limestone, "StairLimestone");
				  GameRegistry.registerBlock(stair_smooth_limestone, "StairSmoothLimestone");
				  GameRegistry.registerBlock(stair_brick_limestone, "StairBrickLimestone");
				  GameRegistry.registerBlock(stair_big_brick_limestone, "StairBigBrickLimestone");
				  GameRegistry.registerBlock(carved_limestone, "CarvedLimestone");
				  GameRegistry.registerBlock(pillar_limestone, "PillarLimestone");
				  GameRegistry.registerBlock(fence_limestone, "FenceLimestone");
				  GameRegistry.registerBlock(wall_limestone, "SmoothWallLimestone");
				  GameRegistry.registerBlock(wall_limestone_brick2, "Brick2WallLimestone");
			  
			  smooth_marble = new CosmeticBlock("SmoothMarble", 2F, "manystones:SmoothMarble");
			  brick1_marble = new CosmeticBlock("Brick1Marble", 2F, "manystones:Brick1Marble");
			  brick2_marble = new CosmeticBlock("Brick2Marble", 2F, "manystones:Brick2Marble");
			  big_brick_marble = new CosmeticBlock("BigBrickMarble", 2F, "manystones:BigBrickMarble");
			  slab_marble = new CosmeticSlab("SlabMarble", 2F, "manystones:BlockMarble");
			  slab_smooth_marble = new CosmeticSlab("SlabSmoothMarble", 2F, "manystones:SmoothMarble");
			  slab_brick1_marble = new CosmeticSlab("SlabBrick1Marble", 2F, "manystones:Brick1Marble");
			  slab_brick2_marble = new CosmeticSlab("SlabBrick2Marble", 2F, "manystones:Brick2Marble");
			  slab_big_brick_marble = new CosmeticSlab("SlabBigBrickMarble", 2F, "manystones:BigBrickMarble");
			  stair_marble = new CosmeticStairs(WorldBlocks.marble, "StairMarble" , 2F, "manystones:StairMarble");
			  stair_smooth_marble = new CosmeticStairs(Decor.smooth_marble, "StairSmoothMarble" , 2F, "manystones:StairSmoothMarble");
			  stair_brick_marble = new CosmeticStairs(Decor.brick2_marble, "StairBrickMarble" , 2F, "manystones:StairBrickMarble");
			  stair_big_brick_marble = new CosmeticStairs(Decor.big_brick_marble, "StairBigBrickMarble" , 2F, "manystones:StairBigBrickMarble");
			  carved_marble = new CosmeticBlock("CarvedMarble", 2F, "manystones:CarvedMarble");
			  pillar_marble = new CosmeticPillar("PillarMarble", 2F, "manystones:PillarMarble");
			  fence_marble = new CosmeticFence(WorldBlocks.marble, "FenceMarble" , 2F, "manystones:BlockMarble");
			  wall_marble= new CosmeticWall(smooth_marble, "WallSmoothMarble", 2F, "manystones:SmoothMarble");
			  wall_marble_brick2= new CosmeticWall(brick2_marble, "WallBrick2Marble", 2F, "manystones:Brick2Marble");
			  
				  GameRegistry.registerBlock(smooth_marble, "SmoothMarble");
				  GameRegistry.registerBlock(brick1_marble, "Brick1Marble");
				  GameRegistry.registerBlock(brick2_marble, "Brick2Marble");
				  GameRegistry.registerBlock(big_brick_marble, "BigBrickMarble");
				  GameRegistry.registerBlock(slab_marble, "SlabMarble");
				  GameRegistry.registerBlock(slab_smooth_marble, "SlabSmoothMarble");
				  GameRegistry.registerBlock( slab_brick1_marble, "SlabBrick1Marble");
				  GameRegistry.registerBlock( slab_brick2_marble, "SlabBrick2Marble");
				  GameRegistry.registerBlock(slab_big_brick_marble, "SlabBigBrickMarble");
				  GameRegistry.registerBlock(stair_marble, "StairMarble");
				  GameRegistry.registerBlock(stair_smooth_marble, "StairSmoothMarble");
				  GameRegistry.registerBlock(stair_brick_marble, "StairBrickMarble");
				  GameRegistry.registerBlock(stair_big_brick_marble, "StairBigBrickMarble");
				  GameRegistry.registerBlock(carved_marble, "CarvedMarble");
				  GameRegistry.registerBlock(pillar_marble, "PillarMarble");
				  GameRegistry.registerBlock(fence_marble, "FenceMarble");
				  GameRegistry.registerBlock(wall_marble, "SmoothWallMarble");
				  GameRegistry.registerBlock(wall_marble_brick2, "Brick2WallMarble");			  

		dark_concrete = new Concrete("DarkConcrete", "manystones:DarkConcrete");
		light_concrete = new Concrete("LightConcrete", "manystones:LightConcrete"); 
		GameRegistry.registerItem(dark_concrete, "DarkConcrete");
		GameRegistry.registerItem(light_concrete, "LightConcrete");	 
		
		
	}
	
}
